export async function exportToPdf(title: string, content: string) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  const lineHeight = 7;
  let y = margin;

  // ヘッダーバー
  doc.setFillColor(108, 99, 255);
  doc.rect(0, 0, pageWidth, 14, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text('LUMINA — AI Business Intelligence Platform', margin, 9);
  doc.text(new Date().toLocaleDateString('ja-JP'), pageWidth - margin, 9, { align: 'right' });

  y = 28;

  // タイトル
  doc.setTextColor(30, 30, 60);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(title, contentWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 10 + 6;

  // 区切り線
  doc.setDrawColor(108, 99, 255);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // 本文処理
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 60);

  const lines = content.split('\n');

  for (const line of lines) {
    if (y > pageHeight - margin - 14) {
      doc.addPage();
      // 新ページヘッダー
      doc.setFillColor(108, 99, 255);
      doc.rect(0, 0, pageWidth, 8, 'F');
      y = 18;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 60);
    }

    const trimmed = line.trim();

    if (trimmed.startsWith('# ')) {
      y += 5;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(15);
      doc.setTextColor(108, 99, 255);
      const wrapped = doc.splitTextToSize(trimmed.slice(2), contentWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 9 + 3;
      // 見出し下線
      doc.setDrawColor(108, 99, 255);
      doc.setLineWidth(0.3);
      doc.line(margin, y - 1, pageWidth - margin, y - 1);
      y += 3;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 60);

    } else if (trimmed.startsWith('## ')) {
      y += 4;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(60, 60, 140);
      const wrapped = doc.splitTextToSize(trimmed.slice(3), contentWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 8 + 2;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 60);

    } else if (trimmed.startsWith('### ')) {
      y += 2;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(80, 80, 160);
      const wrapped = doc.splitTextToSize(trimmed.slice(4), contentWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * lineHeight + 1;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 60);

    } else if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
      const text = trimmed.slice(2);
      doc.setFillColor(108, 99, 255);
      doc.circle(margin + 1.5, y - 1.5, 1, 'F');
      const wrapped = doc.splitTextToSize(text, contentWidth - 7);
      doc.text(wrapped, margin + 5, y);
      y += wrapped.length * lineHeight;

    } else if (trimmed.match(/^\d+\. /)) {
      const match = trimmed.match(/^(\d+)\. (.+)/);
      if (match) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(108, 99, 255);
        doc.text(match[1] + '.', margin, y);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(40, 40, 60);
        const wrapped = doc.splitTextToSize(match[2], contentWidth - 8);
        doc.text(wrapped, margin + 6, y);
        y += wrapped.length * lineHeight;
      }

    } else if (trimmed === '---' || trimmed === '***') {
      doc.setDrawColor(200, 200, 220);
      doc.setLineWidth(0.3);
      doc.line(margin, y, pageWidth - margin, y);
      y += 5;

    } else if (trimmed === '') {
      y += 3;

    } else {
      // **太字** の処理（簡易版）
      const processed = trimmed.replace(/\*\*(.+?)\*\*/g, '$1');
      const wrapped = doc.splitTextToSize(processed, contentWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * lineHeight;
    }
  }

  // フッター（全ページ）
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 180);
    doc.text(
      `Generated by LUMINA AI Platform  |  Page ${i} / ${pageCount}`,
      pageWidth / 2,
      pageHeight - 6,
      { align: 'center' }
    );
    // フッター線
    doc.setDrawColor(200, 200, 220);
    doc.setLineWidth(0.2);
    doc.line(margin, pageHeight - 10, pageWidth - margin, pageHeight - 10);
  }

  const filename = `${title.replace(/[^\w\s]/g, '').slice(0, 30)}_${Date.now()}.pdf`;
  doc.save(filename);
}
