ALTER TABLE pipeline_jobs
  ADD COLUMN IF NOT EXISTS quality_scores JSONB DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS retry_logs JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS quality_threshold INTEGER DEFAULT 70,
  ADD COLUMN IF NOT EXISTS max_retries INTEGER DEFAULT 3,
  ADD COLUMN IF NOT EXISTS auto_improve BOOLEAN DEFAULT TRUE;
